allianceauth/allianceauth

- alliance_auth/settings.py.example
- vagrant/Vagrantfile
- vagrant/bootstrap.sh
Adjusted settings.py.example so everything sensible can be overridden using environment variables.
> Adjust vagrant scripts; enable env variable override

- hrapplications/views.py
Fix for bug causing issues when someone out of alliance trys to go to the application management page.
> Fix for hr_application bug

- alliance_auth/urls.py
- templates/public/base.html
Still trying to figure out how 2 git. Fixing minor typos as a test.
> Fixed typos.

- groupmanagement/admin.py
- groupmanagement/models.py
- groupmanagement/views.py
ensures only staff can manage membership of these groups
Implements feature request in issue #78
> Added ability to hide specific groups from frontend

- services/managers/phpbb3_manager.py
- services/views.py
Sets forum avatar to character portrait on phpbb account creation and password reset.
> phpbb3 avatars

- celerytask/tasks.py
Corrects issue #89 where comparisons were being performed against NoneType alliance models in instances where the corp had no alliance.
> Fix corp/alliance model deletion logic.

- celerytask/tasks.py
Greatly reduces processing time of run_corp_update
> Corrected nested loop in run_corp_update

- alliance_auth/settings.py.example
- celerytask/tasks.py
- eveonline/forms.py
- services/managers/eve_api_manager.py
- stock/templates/registered/addapikey.html
- util/context_processors.py
Added ability to specify API key requirements for members and blues.
Added key checking logic to ensure key access has not changed after registration.
Manual merger of request #98 
Addresses issue #69
> Variable API requirements and key checking

- stock/templates/public/base.html
- timerboard/views.py
- util/__init__.py
Enforced permission on base template for link to timerboard as well as view rendering.
Addresses #15
> Added new permission model to view timer boards.

- stock/templates/registered/timermanagement.html
- timerboard/form.py
- timerboard/models.py
- timerboard/views.py
Fleet name  ->  Details
Fleet Type  ->  Objective
> Modified timer model to include objective status

- eveonline/views.py
- hrapplications/views.py
- stock/templates/registered/corpstats.html
Addresses #116 and more potential 500s. Will prevent the admin account from experiencing 500s.
> Added error handling for missing corp models.

- celerytask/tasks.py
Corrected logic attempting to retrieve data from nonexistant character model.
Also added logic to create character models for new characters on existing API keys.
Closes #110
> More celery fixes.

- alliance_auth/urls.py
- services/forms.py
- services/managers/ipboard_manager.py
- services/managers/mumble_manager.py
- services/managers/openfire_manager.py
- services/managers/phpbb3_manager.py
- services/views.py
- stock/templates/registered/service_password.html
- stock/templates/registered/services.html
mumble, phpbb, ipboard, jabber
Addresses an evemail request.
> Custom service passwords

- requirements.txt
> Fixed Bug #186

- groupmanagement/admin.py
- groupmanagement/models.py
- groupmanagement/views.py
- stock/templates/public/base.html
- stock/templates/registered/services.html
- stock/templates/registered/timermanagement.html
- timerboard/form.py
- timerboard/models.py
- timerboard/views.py
Timerboard doesn't populate local time for corp timers yet.
#170  #169  #137 
Will require syncdb and a migration.
> Implement requests #170 #169 #137

- alliance_auth/settings.py.example
forgot to add it to the settings.py example
> fixed fleet operation installed apps bug

- celerytask/tasks.py
- eveonline/models.py
- services/managers/eve_api_manager.py
> Tolerate random 221 errors from API servers

- celerytask/tasks.py
- eveonline/forms.py
- eveonline/views.py
- services/managers/eve_api_manager.py
- stock/templates/registered/addapikey.html
- util/context_processors.py
Functions to determine membership level by user and character
Re-did api refresh task to correctly assign member states
Main character change correctly assigns states
API add form determines which mask rules to apply based on user state and state of characters on key, but takes twice as long to process
Addresses #192 and #219
> Membership state checks

- services/managers/discord_manager.py
As described in #235, the Discord API is returning incorrect user profiles if commands are executed in quick succession.
This rolls back the api managers to a known working state. Additionally implements security to prevent misuse of auth tokens.
> Revert discord manager to restore functionality

- services/managers/discord_manager.py
Reverts R4stl1n/allianceauth#252
Issue lies in the evewho manager, not the discord manager.
> Revert "Revert discord manager to restore functionality"

- services/managers/phpbb3_manager.py
Clear phpbb user groups when disabled
Addresses #249
> Delete phpbb user session and autologin when disabled

- optimer/form.py
- optimer/views.py
- sigtracker/form.py
- sigtracker/views.py
> Removed Duplicate Forms 

- celerytask/tasks.py
- services/managers/eve_api_manager.py
Holy balls the old one was bad.
This one works.
> New corp update function

- README.md
- alliance_auth/settings.py.example
- alliance_auth/urls.py
- notifications/admin.py
- notifications/context_processors.py
- notifications/handlers.py
- notifications/models.py
- notifications/tests.py
- notifications/views.py
- stock/templates/public/base.html
- stock/templates/registered/notification_list.html
- stock/templates/registered/notification_view.html
- util/__init__.py
Currently only creates notifications for logging events
Addresses #75
New permission `auth | user | logging_notificaions` for users who will get logging notificaions
Icon changes from empty triangle to full when notifications present
New logging block in settings.py to incorporate handler.
> Website Notification System

- celerytask/tasks.py
if corp joins alliance which is blue, it may take 2 cycles for blue status to be reflected due to async  model updates
Addresses #103
> Parallelize corp and alliance model updates

- alliance_auth/settings.py.example
- celerytask/tasks.py
- util/common_task.py
> Toggle assignment of alliance groups

- services/tasks.py
> Functions to clear all data relating to individual services

- celerytask/tasks.py
- groupmanagement/views.py
- hrapplications/views.py
- notifications/__init__.py
- notifications/handlers.py
- stock/templates/registered/notification_view.html
- util/common_task.py
- shorthand notify function to easily create notifications
- notify users when their API key fails refresh for any reason
- notify users when their API key is deleted during a refresh
- notify users when their application is approved, denied or deleted by reviewer
- notify users when their services are disabled.
TODO:
- learn how to send emails. New setting to send email on notification creation, then do it - receivers?
> Batch of User Notifications

- alliance_auth/settings.py.example
- log/.gitignore
folder has been chmod 777 so apache can write
Addresses #282
> Move default logfile location to log folder

- celerytask/tasks.py
- eveonline/forms.py
- services/managers/eve_api_manager.py
allows interpretation of diffferent evelink codes
#298 
Did I miss any?
> Move error handling to api calls

- celerytask/__init__.py
- celerytask/signals.py
- celerytask/tasks.py
- services/views.py
Listen to user group changes, queue service group updates
Should help with #318
> Replace run_databaseUpdate with m2m receiver

- hrapplications/models.py
- hrapplications/views.py
- stock/templates/registered/hrapplicationmanagement.html
- stock/templates/registered/hrapplicationview.html
@orbitroom merged #300 before I finished these.
> Implement additional requests in #305

- alliance_auth/urls.py
- services/forms.py
- services/managers/teamspeak3_manager.py
- services/views.py
- stock/templates/registered/services.html
- stock/templates/registered/teamspeakjoin.html
Will allow groups to sync immediately after account creation.
Adds button to get back to this prompt for users already affected.
Does not sync groups until users join server.
Triggers group sync upon verification.
Closes #331
> Prompt users to join TS when creating account

- hrapplications/models.py
> Fixed unicode support on HR-application extra questions.

- stock/templates/registered/operationmanagement.html
- stock/templates/registered/timermanagement.html
also fixed the corp timer countdown so it shows up correctly
> Added countdown to fleet ops timers

- fleetactivitytracking/views.py
- stock/templates/public/characternotexisting.html
- stock/templates/public/clickfatlinkview.html
- stock/templates/registered/fatlinkmodify.html
- stock/templates/registered/fatlinkview.html
> Fixed a bug with links not registering correctly when undocked. 

- alliance_auth/settings.py.example
- eveonline/forms.py
- eveonline/managers.py
- services/forms.py
- services/managers/discord_manager.py
- services/views.py
When submitting his Discord details, user gets to choose whether to update his discord avatar to eve avatar.
Bonus: some code fixes
> Allows automatic update of Discord avatar to EVE avatar

- celerytask/tasks.py
Beginning of a solution for #448
> Added global tasks to sync all user groups

- stock/templates/public/index.html
> Update index.html for missing double quote

- services/signals.py
Fixes a timing issue where celery workers may process group sync functions before the database transaction has completed. This was resulting in the sync function querying the users old groups rather than the just updated groups.
Depending on the number of workers an installation is running, the number of group sync functions affected may vary from one to, potentially, all of them. In my testing, typically by the time the second sync function is called by the celery worker the transaction has completed and the query data is correct.
This fix forces the groups changed receiver to wait until the transaction complete signal is received before calling the celery group sync functions.
> Fix issue where group syncs process before database transaction completes

- docs/development/index.md
- docs/development/integrating-services.md
- docs/development/menu-hooks.md
- docs/installation/services/discord.md
- docs/installation/services/discourse.md
- docs/installation/services/ipboard3.md
- docs/installation/services/market.md
- docs/installation/services/mumble.md
- docs/installation/services/openfire.md
- docs/installation/services/phpbb3.md
- docs/installation/services/smf.md
- docs/installation/services/teamspeak3.md
- docs/installation/services/xenforo.md
Adds documentation about writing and installing service modules which was missing from #594
> Documentation for Service Modules

- stock/templates/bundles/moment-js.html
- stock/templates/registered/timermanagement.html
The main goal was to fix #685 but I'd rewritten a lot of the timerboard javascript last year chasing a memory leak in chrome, which I never successfully fixed. So I've cherry picked that code to use as a base for this fix.
Also improves i18n by using moments locales.
> Update timerboard javascript

- services/modules/teamspeak3/util/ts3.py
Fixes #578 
Provides Python 2 and 3 compatibility for the Teamspeak 3 interface by replacing sockets with telnetlib.
Also fixed some minor maybe-bugs though I wouldn't expect any major changes in how we interact with TS3.
> Add Teamspeak 3 Py3 compatibility

- fleetactivitytracking/views.py
> Apply ESI endpoint changes for FAT links

- fleetactivitytracking/templates/fleetactivitytracking/fatlinkformatter.html
- stock/templates/registered/addtimer.html
- stock/templates/registered/optimerupdate.html
- stock/templates/registered/srpfleetadd.html
- stock/templates/registered/srpfleetrequest.html
- stock/templates/registered/srpfleetrequestamount.html
- stock/templates/registered/srpfleetupdate.html
- stock/templates/registered/timerupdate.html
There were two pages I missed when switching everything over to CDN based libraries.
Also found a bunch of pages which had libraries included in them that were unnecessary.
> CDN Javascript & CSS fix and cleanup

- alliance_auth/settings.py.example
- authentication/forms.py
- docs/installation/auth/settings.md
- requirements.txt
Added Google reCaptcha to prevent bots from spam registering and brute forcing the login page
Fixes: https://github.com/allianceauth/allianceauth/issues/639
> Added Google reCaptcha

- services/modules/seat/manager.py
- services/modules/seat/views.py
Some users reported issues with the API key sync blocking celery queues. I couldn't find any obvious reason for this but tidied up the key sync method anyway. So far no reports of further blocked queues from the people who tried the updated version.
Cleaned up the manager a little bit.
Added user feedback to views.
> SeAT service cleanup

- docs/installation/auth/dependencies.md
- docs/installation/services/discourse.md
* Update to the Dependency in regard to using SeAT
* Update to the installation of SSL-Certificates with Discourse
* CleanUp of some missing information in the discourse section
> Documentation update

- hrapplications/views.py
This is a backport of #930 to V1 auth (i know i know no new features, but seems useful for the time being)
> Sort Completed HR apps by create date (most recent first)

- timerboard/form.py
Added Refineries, and a Moon Mining Option
Also changed spacing to be consistent and be easier to read
> Updated Structure Choices

- allianceauth/corputils/templates/corputils/corpstats.html
> fix alliancelogo on corp stats page

- allianceauth/optimer/templates/optimer/management.html
- allianceauth/static/js/timers.js
- allianceauth/templates/bundles/moment-js.html
- allianceauth/timerboard/templates/timerboard/view.html
> Timer JS fixes
