allianceauth/allianceauth

- services/managers/util/ts3.py
hotfix for Issue #83 
Prevents comparisons using index of empty objects.
> Corrects string index out of range exception when handling certain TS3 commands

- celerytask/tasks.py
- services/managers/eve_api_manager.py
Avoids attempting to retrieve corp or alliance info for corps or alliances which have closed and deletes the unnecessary models.
Addreses issues #93 and #68
> Added logic to check if corp or alliance exists

- alliance_auth/settings.py.example
- services/managers/openfire_manager.py
Instead of looping through all users, offload the broadcast to Openfire via the broadcast plugin. 
Should greatly improve broadcast speeds.
Addresses #104 
This does however introduce some security issues: mainly that clever users would be able to figure out how to broadcast their own groups. As per the [plugin's readme](https://www.igniterealtime.org/projects/openfire/plugins/broadcast/readme.html), we could get users to set:
plugin.broadcast.disableGroupPermissions    true
plugin.broadcast.groupMembersAllowed        false
plugin.broadcast.allowedUsers               broadcast@yourdomain.com
The broadcast user would need to be an administrator which raises its own security problems, but it's a step in the right direction.
> Broadcast Plugin Support

- registration/forms.py
Allows only letters, numbers and underscores.
Should prevent issue #46 from appearing on new installs.
> Validate usernames during registration.

- services/managers/phpbb3_manager.py
I also re-factored the "__remove_user_from_group" to be more consistent with the "__add_user_to_group" method by moving the cursor into the try.
This should fix issue #171
> Fixing user permission caching within phpBB

- services/managers/eve_api_manager.py
Deletion of characters associated with an API key is logged at INFO.
However, the reason that an API key is marked invalid in the first place is only logged at DEBUG, so if you have debug logging disabled, you won't know why.
> log api key invalidation at INFO level

- services/managers/phpbb3_manager.py
Eve avatar url should be https instead of http so you don't get a mixed content warning if you use https on your forum. The ultimate solution would be http/https agnostic with :// instead, but I don't know if that would work in this file.
> Eve avatar url as https

- services/managers/evewho_manager.py
Fixed an issue where the evewhomanager does not read more than the first 200 members. A limit I had missed...
> EveWho-manager can now read more than 200 members.

- srp/views.py
- stock/templates/registered/srpfleetdata.html
the template rendering for Null values will eventually be taken out its only in there for compatibility as Pending wasn't originally assigned to the database.
> Fixed Error in Template Rendering

- corputils/views.py
- stock/templates/registered/corputils.html
The unregistered characters count is also corrected and a note added when there is a discrepancy between the number of people in corp and the number in EveWho. This adresses #338.
But don't merge yet. This needs to be tested on a server with more users and registered characters than my 5 or so, for performance. Also it needs to be tested with someone who actually experiences the problem with missing characters. Have no such APIs at hand.
> Registered characters not found on EveWho will now be displayed.

- alliance_auth/settings.py.example
- eveonline/forms.py
- eveonline/managers.py
Added automatic rejection of old APIs based on newest API ID on record, per issue #436
> Automatic rejection of old API IDs

- stock/templates/registered/fleetup.html
- stock/templates/registered/fleetupdoctrine.html
- stock/templates/registered/fleetupfittingsview.html
This fix will resolve the 404 (Page not found) error due to a missing "/" in the URL from different links.
fleetup.html row 85
fleetupdoctrin.html row 59
fleetupfittingsview.html row 50
> 404 error when selecting doctrin/fitting

- services/managers/mumble_manager.py
- services/views.py
Under certain circumstances (partial backup restore, table truncate, external management) the AuthServicesInfo and MumbleUser models can become unsynced, preventing a user from deleting or refreshing their Mumble account. This requires services admin to manually remove their mumble username in AuthServicesInfo which will then allow the user to create a new mumble account.
This PR adds a check for already deleted MumbleUser entities if the attempt to delete the users mumble account fails.
> Fix users cannot delete mumble account

- alliance_auth/settings.py.example
- authentication/migrations/0013_service_modules.py
Improves on #594 migrations by refusing to run if the user has missing module destinations for services data which would result in data loss. If the user doesn't care about that data they should, preferably, install that module for the migration and then migrate zero on that module before removing it from `INSTALLED_APPS`. Alternatively they could wipe that columns data in SQL before running the migration again.
Also allows users to specify `SERVICES_MIGRATED=True` to prevent migrations complaining about the order of migrations when enabling a service which was not migrated before the services migration. The 0013 migration will drop all services module migration dependencies if `SERVICES_MIGRATED` is set to True.
> Services Modules migration improvements

- services/modules/mumble/tests.py
- services/modules/mumble/views.py
Celery `Task.apply` takes different arguments to `Task.delay` but unfortunately doesn't throw an exception when you get it wrong and it was failing silently.
Added test to ensure member groups are correctly applied after `activate_mumble` is called.
> Fixed incorrect parameters for mumble update_groups call

- services/modules/discord/tasks.py
- services/modules/discourse/tasks.py
- services/modules/ipboard/tasks.py
- services/modules/mumble/tasks.py
- services/modules/openfire/tasks.py
- services/modules/phpbb3/tasks.py
- services/modules/smf/tasks.py
- services/modules/teamspeak3/tasks.py
Quality of life improvement.
Running tasks manually from a celery shell (`python manage.py celery shell`) can be achieved by running `app.send_task('service_name.task_name')`.
Previously it was possible to run `service_task_name()` to execute a task from a celery task, however as they share a common function name this method clashes with other services, so the new method should be used in place of this.
> Specify short names for service tasks

- hrapplications/views.py
Reported by a user via gitter.
When a character is not in an alliance the search fails as `alliance_name` is None. Since v1.14.2 `alliance_id` and `alliance_name` are now defaulting to `None` instead of an empty string, which I'm fine with.
I searched around for any other similar calls to these two attributes but couldn't find any.
> Prevent HR search from failing with None alliance_name

- services/modules/openfire/manager.py
- services/modules/openfire/tests.py
Fixes #699 
Provides XEP-106 compliant username escaping. Openfire supports XEP-106. Other clients which do not currently support XEP-106 may show the escape characters instead of the correct characters. Go bug the clients developers.
> Implement Openfire username escaping

- services/forms.py
- services/modules/ips4/manager.py
- services/modules/market/manager.py
- stock/templates/registered/service_password.html
Fixes #700
Corrects unsupported `2b` hashes for older versions of PHP. While you could update PHP to get support, there's nothing (presently) wrong with using `2y` in PHP. If you have a _really_ old version of PHP that doesn't support `2y`, then you need to upgrade.
Also removes warnings about plaintext passwords, which no service has anymore, and changes the custom password field from text to password.
I'll attempt to backport the hash fix to 1.14. Edit: Would be a very big change to backport. If you need these fixes you can probably copy the 1.15 manager over the 1.14 manager.
> IPS4 and Market PHP hash fix

- services/modules/teamspeak3/forms.py
- services/modules/teamspeak3/manager.py
- services/modules/teamspeak3/tasks.py
- services/modules/teamspeak3/tests.py
- services/modules/teamspeak3/util/ts3.py
- services/modules/teamspeak3/views.py
Converts manager to instance based instead of static. This allows a single connection to be reused. The class also now makes use of the `__enter__` and `__exit__` magic methods, allowing it to be used with a `with` clause. When the `with` block exits, the connection is automatically torn down instead of being left dangling as it was previously.
This also attempts to address #713, partially by ensuring the connections are closed when they're completed and also by ensuring the response buffer is clear before sending new commands. I'm not particularly hopeful of it being addressed by this though. In my testing I could open up about 1600 TCP connections (in various connection states) to teamspeak running the affected command without any problems. I also think its very unlikely that an entire …
> Teamspeak 3 Updates

- docs/installation/auth/settings.md
- docs/installation/services/openfire.md
- services/modules/openfire/manager.py
- services/modules/openfire/views.py
Removes threading. From my discussion with @Adarnof this tool used to manually message each user which would block for a considerable amount of time. Now it uses the broadcast plugin I think its preferable to block until we have some feedback for the user, given that the process may only take a few seconds. If users report that it is taking an exceedingly long time to send broadcasts after this change I'll have to come up with a better solution.
This also includes changes to prevent SleekXMPP from going into an infinite connection attempt loop under certain circumstances. Stopping the infinite connection loops in `runserver` actually required the kill command to stop even after exiting. It was very, very annoying.
Also added a "hidden" option to disable SSL verification to allow users to …
> Update Openfire broadcast tool

- docs/installation/auth/gunicorn.md
- docs/installation/auth/index.md
Adds documentation for running Alliance Auth with Gunicorn, allowing the use of any HTTP server that supports reverse proxy, in particular NGINX.
> Add Gunicorn docs

- docs/installation/auth/index.md
- docs/installation/auth/nginx.md
Adds some lightweight Nginx setup documentation. Should be enough for most people to get auth working in conjunction with the Gunicorn docs. External services using php-fpm will need some research on the end users behalf, but googling `nginx php-fpm` brings up pages upon pages of guides on how to setup and configure them.
> Nginx docs

- alliance_auth/settings.py.example
- alliance_auth/tests/test_settings.py
- corputils/tasks.py
- docs/installation/auth/quickstart.md
- docs/installation/auth/supervisor.md
- docs/installation/services/teamspeak3.md
- docs/maintenance/troubleshooting.md
- eveonline/tasks.py
- eveonline/views.py
- requirements.txt
- run_alliance_corp_update.py
- thirdparty/Supervisor/auth-celerybeat.conf
- thirdparty/Supervisor/auth-celeryd.conf
Django-celery is effectively obsolete and support for Django 1.8+ has been baked into the base Celery project. This PR replaces `django-celery` with the base `celery` package and `django-celery-beat` providing the scheduling backend.
All of the task decorators have been updated from `@task` or `@scheduled_task` to the new style `@app.task`. Scheduled tasks configuration have been moved into the `settings.py` django config under the `CELERYBEAT_SCHEDULE` variable.
The commands for running the celery functions have changed:
|  | Old | New |
| --- | --- | --- |
| Workers | python manage.py celeryd | celery -A alliance_auth worker |
| Beat | python manage.py celerybeat | celery -A alliance_auth beat |
Currently we have no results backend, but I cant find anywhere we'd be using return values …
> Replace django-celery with base Celery

- alliance_auth/tests/test_settings.py
- services/modules/discord/manager.py
- services/modules/discord/tasks.py
- services/modules/discord/tests.py
- testing-requirements.txt
I wrote this a while ago so I'll let my comment do the talking instead:
Decorator Handles HTTP 429 "Too Many Requests" messages from the Discord API.
If blocking=True is specified, this function will block and retry the function up to max_retries=n times, or 3 if retries is not specified. If the API call still recieves a backoff timer this function will raise a <DiscordApiTooBusy> exception. If the caller chooses blocking=False, the decorator will raise a DiscordApiBackoff exception and the caller can choose to retry after the given timespan available in the retry_after property in seconds.
It doesn't fully handle discords rate limiting headers, instead prevents repeated hits on the API after a 429 backoff has been served. It's also currently only servicing the groups endpoint as that one …
> Discord API rate limiting

- allianceauth/bin/allianceauth.py
- allianceauth/project_template/supervisor.conf
By guessing paths to commands based off the python location, installs not in a virtualenv would fail to generate a supervisor conf with the correct path to `/usr/local/bin/celery` (and gunicorn), instead guessing `/usr/bin/celery` because that's the folder where python is found.
Using [py3's `shutil` library](https://docs.python.org/3/library/shutil.html) it's possible to get the full path to an arbitrary command using [`shutil.which('celery')`](https://docs.python.org/3/library/shutil.html#shutil.which). This means it can tolerate installing inside a venv, globally, and even using development packages installed with `pip install -e`.
Calling the `django-admin startproject` command within `allianceauth start` prevented us from passing custom context to template rendering - this is why the …
> Determine paths to commands using shutil

- allianceauth/hrapplications/views.py
This simply sorts HR apps in the "reviewed" tab by creation date so that the most recent completed apps show first so HR dudes don't have to scroll through or use the search feature for incoming applicants.
> Sort completed HR apps by create date (most recent first)

- docs/features/corpstats.md
If a user copies the example verbatim, celery logs this error:
```
[2018-04-07 14:57:29,930: ERROR/MainProcess] Cannot add entry 'update_all_corpstats' to database schedule: TypeE rror('from_entry() argument after ** must be a mapping, not tuple',). Contents: ({'task': 'allianceauth.corputil s.tasks.update_all_corpstats', 'schedule': <crontab: 0 */6 * * * (m/h/d/dM/MY)>},)
```
> Remove trailing , from CELERYBEAT_SCHEDULE example.

- allianceauth/services/modules/discord/manager.py
I noticed this wasn't working and when I dug down to have a look I noticed that the function in `manager.py` just returns when HTTP status is raised. This suppresses the `@api_backoff` wrapper since it's trying to catch an HTTP Exception.
I believe just taking out the try block should fix the issue.
> Fix 429 spam on discord update_all_nicknames
